Models/Implantation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaForYou.Models
{
    public class Implantation
    {

        public int Id { get; set; }

        [Required(ErrorMessage = "Introduisez une localité")]
        [Display(Name = "Localité")]
        public string Name { get; set; }

        public List<Room> Rooms { get; set; }

        public List<Show> Shows { get; set; }

    }
}

Controllers/ImplantationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CinemaForYou.Models;

namespace CinemaForYou.Controllers
{
    public class ImplantationsController : Controller
    {
        private readonly CinemaForYouDbContext _context;

        public ImplantationsController(CinemaForYouDbContext context)
        {
            _context = context;
        }

        // GET: Implantations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Implantations.ToListAsync());
        }

        // GET: Implantations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var implantation = await _context.Implantations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (implantation == null)
            {
                return NotFound();
            }

            List<Room> rooms = _context.Rooms.Where(r => r.ImplantationId == id).ToList();

            ImplantationManagerViewModel viewModel = new ImplantationManagerViewModel()
            {
                Implantation = implantation,
                Rooms = rooms
            };

            return View(viewModel);
        }

        // GET: Implantations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Implantations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Implantation implantation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(implantation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(implantation);
        }

        // GET: Implantations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var implantation = await _context.Implantations.FindAsync(id);
            if (implantation == null)
            {
                return NotFound();
            }
            return View(implantation);
        }

        // POST: Implantations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Implantation implantation)
        {
            if (id != implantation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(implantation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImplantationExists(implantation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(implantation);
        }

        // GET: Implantations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var implantation = await _context.Implantations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (implantation == null)
            {
                return NotFound();
            }

            return View(implantation);
        }

        // POST: Implantations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var implantation = await _context.Implantations.FindAsync(id);
            _context.Implantations.Remove(implantation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ImplantationExists(int id)
        {
            return _context.Implantations.Any(e => e.Id == id);
        }
    }
}

Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CinemaForYou.Models;

namespace CinemaForYou.Controllers
{
    public class RoomsController : Controller
    {
        private readonly CinemaForYouDbContext _context;

        public RoomsController(CinemaForYouDbContext context)
        {
            _context = context;
        }

        // GET: Rooms
        public async Task<IActionResult> Index()
        {
            var cinemaForYouDbContext = _context.Rooms.Include(r => r.Implantation);
            return View(await cinemaForYouDbContext.ToListAsync());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.Implantation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create(int? id)
        {
            ViewBag.Implantation = _context.Implantations.FirstOrDefault(i => i.Id == id);
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Number,Seats,ImplantationId")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Implantations", new { id = room.ImplantationId });
            }
            ViewData["ImplantationId"] = new SelectList(_context.Implantations, "Id", "Id", room.ImplantationId);
            return View("Details" + room.ImplantationId, "Implantations");
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            ViewData["ImplantationId"] = new SelectList(_context.Implantations, "Id", "Name", room.ImplantationId);
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Number,Seats,ImplantationId")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Implantations", new { id = room.ImplantationId});
            }
            ViewData["ImplantationId"] = new SelectList(_context.Implantations, "Id", "Id", room.ImplantationId);
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.Implantation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Implantations", new { id = room.ImplantationId });
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.Id == id);
        }
    }
}

Views/Implantations/Create.cshtml
@model CinemaForYou.Models.Implantation

@{
    ViewData["Title"] = "Create";
}

<h1>Ajout d'une implantation</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ajouter" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Implantations/Delete.cshtml
@model CinemaForYou.Models.Implantation

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Implantation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Implantations/Details.cshtml
@model CinemaForYou.Models.ImplantationManagerViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Implantation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Implantation.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Implantation.Name)
        </dd>
    </dl>
</div>

<div>
    <h4>Ses salles</h4>
    <table class="table-striped">
        <thead>
        <tr>
            <th>Numéro de la salle</th>
            <th>Nombre de place(s)</th>
        </tr>
        </thead>
        <tbody>
        @foreach (Room room in Model.Rooms)
        {
            <tr>
                <th>@room.Number</th>
                <th>@room.Seats place(s)</th>
                <th class="link-success"><a asp-controller="Rooms" asp-action="Details" asp-route-id="@room.Id">Détails</a></th>
                <th class="link-success"><a asp-controller="Rooms" asp-action="Edit" asp-route-id="@room.Id">Modifier</a></th>
                <th class="link-success"><a asp-controller="Rooms" asp-action="Delete" asp-route-id="@room.Id">Supprimer</a></th>
            </tr>
        }
        </tbody>
    </table>
    <a class="btn btn-success" asp-controller="Rooms" asp-action="Create" asp-route-id="@Model.Implantation.Id">Ajouter une salle</a>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Implantation.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Implantations/Edit.cshtml
@model CinemaForYou.Models.Implantation

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Implantation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sauvegarder" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Implantations/Index.cshtml
@model IEnumerable<CinemaForYou.Models.Implantation>

@{
    ViewData["Title"] = "Index";
}

<h1>Implantations</h1>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a class="btn btn-secondary" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>
<a class="btn btn-success" asp-action="Create">Ajouter une implantation</a>